FROM python:3.7
RUN apt-get update && apt-get install -y python-dev libffi-dev build-essential
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 9090
ENTRYPOINT ["python", "scripts/api.py"]