FROM python:3.7
RUN apt-get update && apt-get install -y python-dev libffi-dev build-essential
COPY requirements.txt /workspace/
WORKDIR /workspace
RUN pip install -r requirements.txt
EXPOSE 8888
ENTRYPOINT ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]