FROM python:3.7
RUN apt-get update && apt-get install -y python-dev libffi-dev build-essential
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
RUN pip install git+https://gitlab.com/dataroots-public/mlmonkey.git
ENV LOG_LEVEL INFO
ENTRYPOINT ["make", "test"]
